stages:
  - tests
  - build

pytest:
  stage: tests
  tags:
    - docker
  image: python:latest
  script:
    - pip install -U pytest pytest-aiohttp pytest-asyncio pytest-cov
    - pytest --cov-report term --cov=aiojsonapi tests/

build:
  stage: build
  tags:
    - docker
  image: python:latest
  script:
    - pip install -U --upgrade setuptools pip twine setuptools wheel
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
